import 'package:flutter/material.dart';
import 'package:flutterapp/interviewapp/generatedhomewidget/generated/GeneratedNavigationBarWidget2.dart';
import 'package:flutterapp/interviewapp/generatedhomewidget/generated/GeneratedFrame22Widget.dart';
import 'package:flutterapp/interviewapp/generatedhomewidget/generated/GeneratedBottomTabBarWidget1.dart';
import 'package:flutterapp/interviewapp/generatedhomewidget/generated/GeneratedCategorylistviewWidget1.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedHome_categoryscollerWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Container(
                width: 375.0,
                height: 812.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 246, 245, 245),
                        ),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 87.0,
                        right: null,
                        bottom: null,
                        width: 375.0,
                        height: 52.0,
                        child: GeneratedCategorylistviewWidget1(),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 139.0,
                        right: null,
                        bottom: null,
                        width: 375.0,
                        height: 602.0,
                        child: GeneratedFrame22Widget(),
                      )
                    ]),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: null,
                bottom: -72.9275131225586,
                width: 375.0,
                height: 72.4637680053711,
                child: GeneratedBottomTabBarWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 86.9565200805664,
                child: GeneratedNavigationBarWidget2(),
              )
            ]),
      ),
    ));
  }
}
