import 'package:flutter/material.dart';
import 'package:flutterapp/interviewapp/generatedhome_categoryscollerwidget/generated/GeneratedProductslistviewWidget1.dart';
import 'package:flutterapp/interviewapp/generatedhome_categoryscollerwidget/generated/GeneratedCategorylistitemWidget.dart';
import 'package:flutterapp/interviewapp/generatedhome_categoryscollerwidget/generated/GeneratedProductslistviewWidget.dart';
import 'package:flutterapp/interviewapp/generatedhome_categoryscollerwidget/generated/GeneratedCategorylistviewWidget.dart';
import 'package:flutterapp/interviewapp/generatedhome_categoryscollerwidget/generated/GeneratedBottomTabBarWidget.dart';
import 'package:flutterapp/interviewapp/generatedhome_categoryscollerwidget/generated/GeneratedNavigationBarWidget.dart';
import 'package:flutterapp/interviewapp/generatedhome_categoryscollerwidget/generated/GeneratedCategorylistitemWidget1.dart';

/* Frame home_category scoller
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHome_categoryscollerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedProductdetailWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 245, 245),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 139.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 51.835853576660156,
                  child: GeneratedCategorylistitemWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 191.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 242.0,
                  child: GeneratedProductslistviewWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 433.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 51.835853576660156,
                  child: GeneratedCategorylistitemWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 485.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 242.0,
                  child: GeneratedProductslistviewWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 812.4637451171875,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 72.4637680053711,
                  child: GeneratedBottomTabBarWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 86.9565200805664,
                  child: GeneratedNavigationBarWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 87.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 52.0,
                  child: GeneratedCategorylistviewWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
