import 'package:flutter/material.dart';
import 'package:flutterapp/interviewapp/generatedprofilewidget/generated/GeneratedFrame21Widget1.dart';
import 'package:flutterapp/interviewapp/generatedprofilewidget/generated/GeneratedFrame20Widget.dart';
import 'package:flutterapp/interviewapp/generatedprofilewidget/generated/GeneratedPaymentsummaryWidget2.dart';
import 'package:flutterapp/interviewapp/generatedprofilewidget/generated/GeneratedBottomTabBarWidget2.dart';
import 'package:flutterapp/interviewapp/generatedprofilewidget/generated/GeneratedNavigationBarWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/interviewapp/generatedprofilewidget/generated/GeneratedBodybolddarkWidget17.dart';
import 'package:flutterapp/interviewapp/generatedprofilewidget/generated/GeneratedIconchevronleftWidget.dart';

/* Frame profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 246, 245, 245),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 86.9565200805664,
                child: GeneratedNavigationBarWidget3(),
              ),
              Positioned(
                left: 15.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconchevronleftWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 22.0,
                child: GeneratedBodybolddarkWidget17(),
              ),
              Positioned(
                left: -4.0,
                top: 108.95654296875,
                right: null,
                bottom: null,
                width: 383.0,
                height: 60.0,
                child: GeneratedFrame20Widget(),
              ),
              Positioned(
                left: -4.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 108.0,
                child: GeneratedFrame21Widget1(),
              ),
              Positioned(
                left: -4.0,
                top: 190.95654296875,
                right: null,
                bottom: null,
                width: 383.0,
                height: 112.0,
                child: GeneratedPaymentsummaryWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.08924109360267377;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 1.0005712650092364,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBottomTabBarWidget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
