import 'package:flutter/material.dart';
import 'package:flutterapp/interviewapp/generatedsplashscreenwidget/generated/GeneratedFrame29Widget.dart';

/* Frame splash screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedHomeWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Image.asset(
                    "assets/images/f2a29de81d2cab869a0569f2ad970cf098e0570a.png",
                    color: null,
                    fit: BoxFit.cover,
                    width: 375.0,
                    height: 812.0,
                    colorBlendMode: BlendMode.dstATop,
                  ),
                ),
                Positioned(
                  left: 100.0,
                  top: 318.0,
                  right: null,
                  bottom: null,
                  width: 175.0,
                  height: 175.0,
                  child: GeneratedFrame29Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
